version: '3.3'

services:
  joomla:
    image: joomla:latest
    ports:
      - "8080:80"
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: "Admin123!"
      JOOMLA_DB_NAME: joomla

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "Admin123!"
      MYSQL_DATABASE: joomla